spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.vectorstore.mariadb.initialize-schema=true