spring.application.name=demo

spring.datasource.url=jdbc:mariadb://localhost:3306/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# 주문 목록 알려 줘.
spring.ai.mcp.client.streamable-http.connections.product-order-server.url=http://localhost:8090

# 스프링부트에 대해 간략하게 정리해서 springboot-summary.txt로 저장해 줘.
# 지금 몇시야?
spring.ai.mcp.client.stdio.connections.datetime.command=java.exe
spring.ai.mcp.client.stdio.connections.datetime.args=-jar,./support/mcp-server-stdio.jar

# 스프링 AI에 대해 요약하여 "스프링 AI 요약"이라는 제목의 페이지 작성해 줘.
# 회의 내용 요약해서 회의록-{날짜} 제목의 페이지 작성해 줘.
spring.ai.mcp.client.stdio.connections.notion.command=npx.cmd
spring.ai.mcp.client.stdio.connections.notion.args=-y,@notionhq/notion-mcp-server
spring.ai.mcp.client.stdio.connections.notion.env.NOTION_TOKEN=${NOTION_TOKEN}
